site_name: COGIP Tools

repo_name: cogip/simulation
repo_url: https://github.com/cogip/simulation

theme:
  name: 'material'
  language: en
  # palette:
  #   scheme: slate
  #   primary: blue grey

nav:
  - Overview: index.md
  - Setup: install.md
  - Tools:
    - usage/server.md
    - usage/server_beacon.md
    - usage/planner.md
    - usage/copilot.md
    - usage/detector.md
    - usage/monitor.md
    - usage/dashboard.md
    - usage/dashboard_beacon.md
    - usage/robotcam.md
    - usage/beaconcam.md
    - usage/camera.md
    - usage/replay.md
    - usage/lidarusb.md
  - Raspberry Pi OS: raspios.md
  - Developer's Doc:
    - Introduction: developers/developers.md
    - Modules: reference/
    - Dashboard: developers/dashboard.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: no
            heading_level: 2
            members_order: source
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock
            - sys.modules["Shiboken"] = MagicMock()
            - from cogip.tools.copilot import pbcom
            - pbcom.AioSerial = MagicMock()
            - from PySide6.support.signature import parser
            - parser.pyside_type_init = MagicMock()
            - import asyncio
            - asyncio.get_running_loop = MagicMock()
          selection:
            new_path_syntax: true

  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md

  - search

watch:
  - cogip

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"
      baselevel: 1
