site_name: COGIP Tools

repo_name: cogip/simulation
repo_url: https://github.com/cogip/simulation

theme:
  name: 'material'
  language: en
  # palette:
  #   scheme: slate
  #   primary: blue grey

nav:
  - Overview: index.md
  - Installation: install.md
  - Usage:
    - usage/monitor.md
    - usage/copilot.md
    - usage/replay.md
    - usage/lidarusb.md
    - usage/lidarpf.md
  - Developer's Doc:
    - Introduction: developers/developers.md
    - Modules: reference/

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: no
            heading_level: 2
            members_order: source
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock
            - sys.modules["Shiboken"] = MagicMock()
          selection:
            new_path_syntax: true
      watch:
        - cogip

  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md

  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"
      baselevel: 1
