site_name: COGIP Simulator

repo_name: cogip/simulation
repo_url: https://github.com/cogip/simulation

theme:
  name: 'material'
  language: en
  # palette:
  #   scheme: slate
  #   primary: blue grey

nav:
  - Overview: index.md
  - Installation: install.md
  - Usage:
    - usage/simulator.md
    - usage/lidarusb.md
    - usage/lidarpf.md
  - Developer's Doc:
    - Introduction: developers/developers.md
    - Modules:
      - cogip:
        - tools:
          - simulator:
            - __main__.py: developers/modules/cogip/tools/simulator/main.md
            - mainwindow.py: developers/modules/cogip/tools/simulator/mainwindow.md
            - serialcontroller.py: developers/modules/cogip/tools/simulator/serialcontroller.md
          - lidarusb:
            - __main__.py: developers/modules/cogip/tools/lidarusb/main.md
            - dataproxy.py: developers/modules/cogip/tools/lidarusb/dataproxy.md
            - lidarserial.py: developers/modules/cogip/tools/lidarusb/lidarserial.md
            - mainwindow.py: developers/modules/cogip/tools/lidarusb/mainwindow.md
          - lidarpf:
            - __main__.py: developers/modules/cogip/tools/lidarpf/main.md
            - dataproxy.py: developers/modules/cogip/tools/lidarpf/dataproxy.md
            - lidarserial.py: developers/modules/cogip/tools/lidarpf/lidarserial.md
            - mainwindow.py: developers/modules/cogip/tools/lidarpf/mainwindow.md
        - entities:
          - asset.py: developers/modules/cogip/entities/asset.md
          - dynobstacle.py: developers/modules/cogip/entities/dynobstacle.md
          - impact.py: developers/modules/cogip/entities/impact.md
          - line.py: developers/modules/cogip/entities/line.md
          - obstacle.py: developers/modules/cogip/entities/obstacle.md
          - robot.py: developers/modules/cogip/entities/robot.md
          - sensor.py: developers/modules/cogip/entities/sensor.md
        - widgets:
          - chartsview.py: developers/modules/cogip/widgets/chartsview.md
          - gameview.py: developers/modules/cogip/widgets/gameview.md
          - lidarview.py: developers/modules/cogip/widgets/lidarview.md
        - models:
          - models.py: developers/modules/cogip/models/models.md
        - utils:
          - lidartablemodel: developers/modules/cogip/utils/lidartablemodel.md
        - config.py: developers/modules/cogip/config.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["Shiboken"] = mock()
      watch:
        - cogip

  - search


markdown_extensions:
  - admonition
  - codehilite
