from .beacon import BeaconNamespace  # noqa
from .copilot import CopilotNamespace  # noqa
from .dashboard import DashboardNamespace  # noqa
from .detector import DetectorNamespace  # noqa
from .firmware_parameters import FirmwareParametersNamespace  # noqa
from .firmware_telemetry import FirmwareTelemetryNamespace  # noqa
from .monitor import MonitorNamespace  # noqa
from .planner import PlannerNamespace  # noqa
from .robotcam import RobotcamNamespace  # noqa
