# CLASS=ROBOT (ROBOT_ID=1). Resolved from config-robots.env. ROBOT_ID is the
# only build-time substitution (809ROBOT_ID -> the socketio port).

# General
VIRTUAL_ENV=/opt/.venv
COGIP_SOCKETIO_SERVER_URL=http://localhost:809ROBOT_ID
AVOIDANCE_DEBUG=0
PLANNER_DEBUG=0

# Copilot
COPILOT_CAN_CHANNEL=can0

# Planner
PLANNER_ROBOT_WIDTH=295
PLANNER_ROBOT_LENGTH=289
PLANNER_OBSTACLE_BB_MARGIN=0.2
PLANNER_BYPASS_DETECTOR=0
PLANNER_STARTER_PIN=17
PLANNER_SCSERVOS_PORT=/dev/ttyACM0
PLANNER_SCSERVOS_BAUD_RATE=1000000

# Detector
DETECTOR_LIDAR_PORT=/dev/ttyAMA4
DETECTOR_MIN_DISTANCE=150
DETECTOR_MAX_DISTANCE=1800
DETECTOR_MIN_INTENSITY=0
DETECTOR_REFRESH_INTERVAL=0.1
DETECTOR_CLUSTER_MIN_SAMPLES=1
DETECTOR_CLUSTER_EPS=30.0
DETECTOR_SENSOR_DELAY=0

# MCU Logger
MCU_LOGGER_PORT=/dev/ttyAMA2

# Robotcam (Raspberry Pi Camera Global Shutter)
ROBOTCAM_NAME="rpicam"
ROBOTCAM_CODEC="yuyv"
ROBOTCAM_WIDTH=728
ROBOTCAM_HEIGHT=544

# Camera
CAMERA_NAME="rpicam"
CAMERA_CODEC="yuyv"
CAMERA_WIDTH=728
CAMERA_HEIGHT=544
