properties_schema = {
    "title": "Planner Properties",
    "namespace": "/planner",
    "sio_event": "config_updated",
    "properties": {
        "robot_width": {
            "title": "Robot_width",
            "description": "Width of the robot (mm)",
            "type": "integer",
            "maximum": 1000,
            "minimum": 100,
            "default": 295,
        },
        "robot_length": {
            "title": "Robot Length",
            "type": "integer",
            "description": "Length of the robot (mm)",
            "maximum": 1000,
            "minimum": 100,
            "default": 295,
        },
        "obstacle_radius": {
            "title": "Obstacle Radius",
            "description": "Radius of a dynamic obstacle (mm)",
            "type": "integer",
            "maximum": 1000,
            "minimum": 100,
            "default": 150,
        },
        "obstacle_bb_margin": {
            "title": "Bounding Box Margin",
            "description": "Obstacle bounding box margin in percent of the radius (%)",
            "type": "number",
            "maximum": 1.0,
            "minimum": 0.0,
            "multipleOf": 0.01,
            "default": 0.2,
        },
        "obstacle_bb_vertices": {
            "title": "Bounding Box Vertices",
            "description": "Number of obstacle bounding box vertices",
            "type": "integer",
            "maximum": 20,
            "minimum": 3,
            "default": 6,
        },
        "obstacle_updater_interval": {
            "title": "Obstacle Updater Interval",
            "description": "Interval between each obstacles list update (seconds)",
            "type": "number",
            "maximum": 2.0,
            "minimum": 0.05,
            "multipleOf": 0.05,
            "default": 0.1,
        },
        "path_refresh_interval": {
            "title": "Path Refresh Interval",
            "description": "Interval between each update of robot paths (seconds)",
            "type": "number",
            "maximum": 2.0,
            "minimum": 0.001,
            "multipleOf": 0.001,
            "default": 0.2,
        },
        "bypass_detector": {
            "title": "Bypass Detector",
            "description": "Use perfect obstacles from monitor instead of detected obstacles by Lidar",
            "type": "boolean",
            "default": False,
        },
        "disable_fixed_obstacles": {
            "title": "Disable Fixed Obstacles",
            "description": "Disable fixed obstacles. Useful to work on Lidar obstacles and avoidance",
            "type": "boolean",
            "default": True,
        },
        "goap_depth": {
            "title": "GOAP Depth",
            "description": "Depth of the GOAP search tree, 0 to disable GOAP",
            "type": "integer",
            "maximum": 255,
            "minimum": 0,
            "default": 0,
        },
    },
}
