# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PB_Controller.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'PB_Controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PB_Controller.proto\"/\n\rPB_Controller\x12\x1e\n\x02id\x18\x01 \x01(\x0e\x32\x12.PB_ControllerEnum*\xe4\x01\n\x11PB_ControllerEnum\x12\x0b\n\x07QUADPID\x10\x00\x12\x18\n\x14LINEAR_POSE_DISABLED\x10\x01\x12\x13\n\x0fQUADPID_TRACKER\x10\x02\x12\x17\n\x13LINEAR_SPEED_TUNING\x10\x03\x12\x18\n\x14\x41NGULAR_SPEED_TUNING\x10\x04\x12\x16\n\x12LINEAR_POSE_TUNING\x10\x05\x12\x17\n\x13\x41NGULAR_POSE_TUNING\x10\x06\x12\x14\n\x10LINEAR_POSE_TEST\x10\x07\x12\x19\n\x15\x41\x44\x41PTIVE_PURE_PURSUIT\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_Controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PB_CONTROLLERENUM']._serialized_start=73
  _globals['_PB_CONTROLLERENUM']._serialized_end=301
  _globals['_PB_CONTROLLER']._serialized_start=23
  _globals['_PB_CONTROLLER']._serialized_end=70
# @@protoc_insertion_point(module_scope)
