# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PB_ParameterCommands.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'PB_ParameterCommands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aPB_ParameterCommands.proto\"\xbf\x01\n\x11PB_ParameterValue\x12\x15\n\x0b\x66loat_value\x18\x01 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x02 \x01(\x01H\x00\x12\x15\n\x0bint32_value\x18\x03 \x01(\x05H\x00\x12\x16\n\x0cuint32_value\x18\x04 \x01(\rH\x00\x12\x15\n\x0bint64_value\x18\x05 \x01(\x03H\x00\x12\x16\n\x0cuint64_value\x18\x06 \x01(\x04H\x00\x12\x14\n\nbool_value\x18\x07 \x01(\x08H\x00\x42\x07\n\x05value\"*\n\x16PB_ParameterGetRequest\x12\x10\n\x08key_hash\x18\x01 \x01(\r\"N\n\x17PB_ParameterGetResponse\x12\x10\n\x08key_hash\x18\x01 \x01(\r\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.PB_ParameterValue\"M\n\x16PB_ParameterSetRequest\x12\x10\n\x08key_hash\x18\x01 \x01(\r\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.PB_ParameterValue\"P\n\x17PB_ParameterSetResponse\x12\x10\n\x08key_hash\x18\x01 \x01(\r\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.PB_ParameterStatus*G\n\x12PB_ParameterStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x15\n\x11VALIDATION_FAILED\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_ParameterCommands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PB_PARAMETERSTATUS']._serialized_start=509
  _globals['_PB_PARAMETERSTATUS']._serialized_end=580
  _globals['_PB_PARAMETERVALUE']._serialized_start=31
  _globals['_PB_PARAMETERVALUE']._serialized_end=222
  _globals['_PB_PARAMETERGETREQUEST']._serialized_start=224
  _globals['_PB_PARAMETERGETREQUEST']._serialized_end=266
  _globals['_PB_PARAMETERGETRESPONSE']._serialized_start=268
  _globals['_PB_PARAMETERGETRESPONSE']._serialized_end=346
  _globals['_PB_PARAMETERSETREQUEST']._serialized_start=348
  _globals['_PB_PARAMETERSETREQUEST']._serialized_end=425
  _globals['_PB_PARAMETERSETRESPONSE']._serialized_start=427
  _globals['_PB_PARAMETERSETRESPONSE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
