# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PB_PathPose.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'PB_PathPose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PB_PathPose.proto\x1a\rPB_Pose.proto\"\x82\x02\n\x0bPB_PathPose\x12\x16\n\x04pose\x18\x01 \x01(\x0b\x32\x08.PB_Pose\x12\x1e\n\x16max_speed_ratio_linear\x18\x02 \x01(\r\x12\x1f\n\x17max_speed_ratio_angular\x18\x03 \x01(\r\x12-\n\x10motion_direction\x18\x04 \x01(\x0e\x32\x13.PB_MotionDirection\x12\x1c\n\x14\x62ypass_anti_blocking\x18\x05 \x01(\x08\x12\x12\n\ntimeout_ms\x18\x06 \x01(\r\x12 \n\x18\x62ypass_final_orientation\x18\x07 \x01(\x08\x12\x17\n\x0fis_intermediate\x18\x08 \x01(\x08*L\n\x12PB_MotionDirection\x12\x11\n\rBIDIRECTIONAL\x10\x00\x12\x10\n\x0c\x46ORWARD_ONLY\x10\x01\x12\x11\n\rBACKWARD_ONLY\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_PathPose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PB_MOTIONDIRECTION']._serialized_start=297
  _globals['_PB_MOTIONDIRECTION']._serialized_end=373
  _globals['_PB_PATHPOSE']._serialized_start=37
  _globals['_PB_PATHPOSE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
