# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_PowerSupply.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PB_PowerSupply.proto\"e\n\x13PB_PowerRailsStatus\x12\x12\n\np3V3_pgood\x18\x01 \x01(\x08\x12\x12\n\np5V0_pgood\x18\x02 \x01(\x08\x12\x12\n\np7V5_pgood\x18\x03 \x01(\x08\x12\x12\n\npxVx_pgood\x18\x04 \x01(\x08\"F\n\x14PB_PowerSourceStatus\x12\x15\n\rbattery_valid\x18\x01 \x01(\x08\x12\x17\n\x0f\x64\x63_supply_valid\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_PowerSupply_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PB_POWERRAILSSTATUS._serialized_start=24
  _PB_POWERRAILSSTATUS._serialized_end=125
  _PB_POWERSOURCESTATUS._serialized_start=127
  _PB_POWERSOURCESTATUS._serialized_end=197
# @@protoc_insertion_point(module_scope)
