# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PB_State.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'PB_State.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB_Polar_pb2 as PB__Polar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePB_State.proto\x1a\x0ePB_Polar.proto\"[\n\x08PB_State\x12\r\n\x05\x63ycle\x18\x02 \x01(\r\x12 \n\rspeed_current\x18\x03 \x01(\x0b\x32\t.PB_Polar\x12\x1e\n\x0bspeed_order\x18\x04 \x01(\x0b\x32\t.PB_Polarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PB_State_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PB_STATE']._serialized_start=34
  _globals['_PB_STATE']._serialized_end=125
# @@protoc_insertion_point(module_scope)
