name: Build wheel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-wheel:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3.2.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build wheel
          run: |
            docker compose pull build_wheel
            docker compose up build_wheel

        - name: Check if wheel exists
          run: |
            ls -lha dist
            find dist/*_aarch64.whl || (echo "Wheel not found" && exit 1)
