name: Build Documentation using MkDocs
on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Deploy doc
        run: |
          mkdocs gh-deploy
