name: Build Documentation using MkDocs
on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Install Debian dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libegl1

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install

      - name: Create .venv
        run: uv venv

      - name: Patch Python install
        run: uvx --isolated --from "git+https://github.com/bluss/sysconfigpatcher" sysconfigpatcher $(dirname $(dirname $(readlink .venv/bin/python)))

      - name: Install the packages
        run: uv sync --all-extras --dev

      - name: Deploy doc
        run: uv run mkdocs gh-deploy --force

      - name: Minimize uv cache
        run: uv cache prune --ci
