name: Build Documentation using MkDocs
on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Debian dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libegl1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Deploy doc
        run: |
          mkdocs gh-deploy --force
