name: Build Documentation using MkDocs
on: 
  push: 
    branches: [master] 

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy
