name: Build Documentation using MkDocs
on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Install Debian dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libegl1

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.11"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dependencies
        run: uv sync --no-install-project

      - name: Deploy doc
        run: uv run --no-sync --no-project mkdocs gh-deploy --force

      - name: Minimize uv cache
        run: uv cache prune --ci
